#67 ETCD modul konfiguracio beallitas modositasa
i-Cell-Mobilsoft-Open-Source/coffee pull request #111
Opened 2020-12-03 09:50 UTC by cserhatit

2020-12-03 13:26 UTC, rombow requested changes

2020-12-03 13:26 UTC, rombow commented on docs/migration/migration120to130.adoc
> +A Wildfly Swarm konfigurációban ki kell egészíteni az `etcd.default.url` kulcsot a `coffee.` prefix-szel.
a coffee nem alkalmazas fuggo

2020-12-03 13:26 UTC, rombow commented on docs/howto/etcd.adoc
> +hogy a Wildfly Swarm konfigurációjában meghatározott `coffee.etcd.default.url`
Wildfly Swarm nem kell ide, regi tevedes

2020-12-03 15:35 UTC, rombow approved these changes

2020-12-03 15:46 UTC, czenczl approved these changes

2020-12-04 12:51 UTC, bucherarnold approved these changes

2020-12-04 13:17 UTC, merged