#87 BatchService handle collections
i-Cell-Mobilsoft-Open-Source/coffee pull request #112
Opened 2020-12-03 10:53 UTC by cserhatit

2020-12-03 13:25 UTC, rombow requested changes

2020-12-03 13:25 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
> +     * @param entities
ha mar bele van nyúlva a javadocba akkor javítsuk ki légyszíves, kell a paraméterekhez leírás, mert így invalid

2020-12-03 15:35 UTC, rombow approved these changes

2020-12-03 15:47 UTC, czenczl approved these changes

2020-12-04 12:50 UTC, bucherarnold approved these changes

2020-12-04 13:16 UTC, merged