multiple-catalog-usage
i-Cell-Mobilsoft-Open-Source/coffee pull request #132
Opened 2021-01-29 09:55 UTC by lacipadar

Lényeg: Minden maven artifact be tudja dobni a "közösbe" a saját catalog-ját, így nem globális a catalog-ok halmazának felvétele.

2021-02-01 19:43 UTC, bucherarnold commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +            log.info("Catalog registry found: [{0}]", cr.getClass().getName());
ez debug szinten jobb lenne

2021-02-01 19:43 UTC, bucherarnold commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +        List<String> list = new ArrayList<String>();
beszedesebb legyen a valtozo neve

2021-02-01 19:43 UTC, bucherarnold commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +                if (!list.contains(path)) {
ha list helyett set-et hasznalnal nem kene bele ez az ellenorzes

2021-02-01 19:43 UTC, bucherarnold commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +                    log.info("Registered catalog path found: [{0}]", path);
ez is debug legyen legyszi

2021-02-01 19:43 UTC, bucherarnold commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +            }
format

2021-02-02 10:01 UTC, rombow requested changes

2021-02-02 12:10 UTC, czenczl commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +    private Instance<ICatalogRegistry> registries;
lehetne a CatalogProducer @Model helyett @ApplicationScoped mert igy mindig ujrapeldanyosodik amikor a producer hívódik

2021-02-02 12:11 UTC, czenczl requested changes

2021-02-02 12:11 UTC, czenczl commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
> +                URI catalogUri = CatalogProducer.class.getClassLoader().getResource(catalogPath).toURI();
erre jó lenne valami cache, most minden xml validaciora felolvassuk ujra és ujra

2021-02-03 12:28 UTC, closed without merging