#29 Fordítási Javadoc hibák javítása
i-Cell-Mobilsoft-Open-Source/coffee pull request #138
Opened 2021-02-03 12:19 UTC by jhamrak

2021-02-03 12:24 UTC, speter555 commented
Ezt a sok javítást lehet úgy lenne érdemes ellenőrizni hogy a maven adott fázisa rendesen lefut-e, ha igen akkor szuper, ha nem akkor tudjuk hol kell még javítani. Végső soron ez a feladat azért is jött létre hogy azt a részt visszakapcsolhassuk ami a javadoc-okat ellenőrzi.

2021-02-03 13:33 UTC, rombow commented
Sajnos meg mindig vannak hibak, hogyha a fo pom.xml-ben berakod ezt:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>3.2.0</version>
    <configuration>
        <failOnError>true</failOnError>
        <failOnWarnings>true</failOnWarnings>
        <excludePackageNames>hu.icellmobilsoft.coffee.dto.common.*</excludePackageNames>
    </configuration>
</plugin>
```
Valamiert ez nem blokkolja be ha hiba van:
mvn -Dmaven.javadoc.failOnError=true -Dmaven.javadoc.failOnWarnings=true javadoc:javadoc

2021-02-03 13:37 UTC, rombow requested changes
coffee-se-logging -ban meg jelzi hogy nem jo a javadoc

2021-02-03 14:29 UTC, jhamrak commented
> Sajnos meg mindig vannak hibak, hogyha a fo pom.xml-ben berakod ezt:
> 
> ```
> <plugin>
>     <groupId>org.apache.maven.plugins</groupId>
>     <artifactId>maven-javadoc-plugin</artifactId>
>     <version>3.2.0</version>
>     <configuration>
>         <failOnError>true</failOnError>
>         <failOnWarnings>true</failOnWarnings>
>         <excludePackageNames>hu.icellmobilsoft.coffee.dto.common.*</excludePackageNames>
>     </configuration>
> </plugin>
> ```
> 
> Valamiert ez nem blokkolja be ha hiba van:
> mvn -Dmaven.javadoc.failOnError=true -Dmaven.javadoc.failOnWarnings=true javadoc:javadoc

Én azt tapasztalom, hogy így beleszalad a generált DTO-kba, pl. `hu.icellmobilsoft.coffee.dto.notification.notification` alatt. Módosított exclude-okkal nekem lefut végig sikeresen:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>3.2.0</version>
	<configuration>
		<failOnError>true</failOnError>
		<failOnWarnings>true</failOnWarnings>
			<excludePackageNames>
				hu.icellmobilsoft.coffee.dto.common.*:hu.icellmobilsoft.coffee.dto.notification.*:hu.icellmobilsoft.coffee.dto.document.*
			</excludePackageNames>
	</configuration>
</plugin>
```

2021-02-03 15:20 UTC, rombow commented
[WARNING] Javadoc Warnings
[WARNING] **/coffee/coffee-se/coffee-se-logging/src/main/java/hu/icellmobilsoft/coffee/se/logging/Logger.java:36: warning: no @return
[WARNING] public static hu.icellmobilsoft.coffee.se.logging.Logger getLogger(Class<?> clazz) {
[WARNING] ^
[WARNING] **/coffee/coffee-se/coffee-se-logging/src/main/java/hu/icellmobilsoft/coffee/se/logging/Logger.java:46: warning: no @return
[WARNING] public static hu.icellmobilsoft.coffee.se.logging.Logger getLogger(String name) {
[WARNING] ^
[WARNING] **/coffee/coffee-se/coffee-se-logging/src/main/java/hu/icellmobilsoft/coffee/se/logging/Logger.java:55: warning: no @param for logger
[WARNING] void setLogger(java.util.logging.Logger logger);
[WARNING] ^
[WARNING] **/coffee/coffee-se/coffee-se-logging/src/main/java/hu/icellmobilsoft/coffee/se/logging/Logger.java:62: warning: no @return
[WARNING] java.util.logging.Logger getLogger();
[WARNING] ^

2021-02-03 15:39 UTC, jhamrak commented
Ez fura, a mai [#29 Fixing Javadoc errors in module: coffee-se-logging](https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/pull/138/commits/4552828109b1fd20ede255669dd59a7831f9aa17) commitom pont ezeket a hibákat javította. Nekem meg is jelenik kódban is, meg itt is a commitok között.

2021-02-03 16:00 UTC, rombow commented
> Ez fura, a mai [#29 Fixing Javadoc errors in module: coffee-se-logging](https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/pull/138/commits/4552828109b1fd20ede255669dd59a7831f9aa17) commitom pont ezeket a hibákat javította. Nekem meg is jelenik kódban is, meg itt is a commitok között.

Oh Bocsi, nem vettem eszre hogy kozben modosult a branch prefixe es nalam meg a regit hasznaltam es regi volt. Igy mar tenyleg jo!

2021-02-03 16:00 UTC, rombow approved these changes

2021-02-03 19:51 UTC, czenczl approved these changes

2021-02-03 21:03 UTC, vasizs approved these changes

2021-02-04 17:03 UTC, bucherarnold approved these changes

2021-02-08 10:35 UTC, merged