Dateutil bovites
i-Cell-Mobilsoft-Open-Source/coffee pull request #166
Opened 2021-05-13 14:49 UTC by akbence

#161 
Egy projectből átemelve, kiegészítve tesztekkel

2021-05-13 15:49 UTC, rombow requested changes

2021-05-13 15:49 UTC, rombow commented on coffee-tool/src/test/java/hu/icellmobilsoft/coffee/tool/utils/date/DateUtilTest.java
> +        assertNotNull(actual);
ennek es a kovetkezo tesztnek nincs sok ertelme

2021-05-14 10:30 UTC, rombow approved these changes

2021-05-17 09:44 UTC, bucherarnold approved these changes

2021-05-17 12:45 UTC, petrenyi-mark approved these changes

2021-05-17 13:10 UTC, merged