#171 - DefaultExceptionMessageTranslator kiegeszites
i-Cell-Mobilsoft-Open-Source/coffee pull request #173
Opened 2021-05-27 10:43 UTC by tamkarcsi

2021-05-27 10:47 UTC, Balazs-Joo submitted a review, later dismissed

2021-05-27 11:18 UTC, tamkarcsi commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultExceptionMessageTranslator.java
> +            String applicationName = InitialContext.doLookup("java:app/AppName");
A t instanceof RestClientResponseException-nel itt valoszinu abbol kell atmasolni, tobb kliens hivasnal az eredeti lecserelodik ezen a ponton, igaz VDR-nel az applicationName minden modulra ROOT,

2021-05-27 12:20 UTC, bucherarnold submitted a review, later dismissed

2021-05-27 16:56 UTC, czenczl commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/IExceptionMessageTranslator.java
> +    void addCommonInfo(BaseExceptionResultType dto, Throwable t, Enum<?> faultType);
migracios doksiba beleírod légyszi?

2021-05-27 16:56 UTC, czenczl approved these changes

2021-05-27 19:01 UTC, rombow requested changes

2021-05-27 19:01 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultExceptionMessageTranslator.java
> +            String applicationName = InitialContext.doLookup("java:app/AppName");
Erre a nev megszerzesre ki kell talalni valami kulcsot vagy mas lehetoseget, hogy ne fuggjon csak az EE nev megadastol

2021-05-31 06:25 UTC, rombow requested changes

2021-05-31 06:25 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/log/BaseRestLogger.java
> +    @ConfigProperty(name = "service.name")
Ennek a konfig kulcsnak a bevezeteset nem lehet elvarni hogy mindenki megtegye. Kell szamolni valami alapertelmezett ertekkel is, majd a coffee konfig parametereibe is beilleszteni, jelen esetben "coffee." prefixet hasznalnak, beszeljunk a megoldasokrol...

2021-06-18 07:39 UTC, rombow requested changes

2021-06-18 07:39 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/cdi/BaseApplicationContainer.java
> +            String coffeeAppNameConfig = applicationConfiguration.getString(COFFEE_APP_NAME);
applicationConfiguration jelenl esetben nem hasznalhato, mert van benne request scope bean hasznalat. Itt most a klasszikus MP-config lekerdezes kell

2021-06-18 08:46 UTC, closed without merging

2021-06-18 08:46 UTC, tamkarcsi commented
Hibas issue szam miatt uj PR-t kuldtem.