Feature/osp 35 utcoffsettimexmladapter utcoffsetdatetimexmladapter implementation 160
i-Cell-Mobilsoft-Open-Source/coffee pull request #188
Opened 2021-08-27 11:00 UTC by kovacsgpeter

2021-08-30 07:19 UTC, rombow approved these changes

2021-08-30 07:22 UTC, martin-nagy submitted a review, later dismissed

2021-09-01 07:35 UTC, bucherarnold approved these changes

2021-09-07 05:42 UTC, vasizs submitted a review, later dismissed

2021-09-27 06:59 UTC, rombow approved these changes

2021-09-27 07:04 UTC, bucherarnold commented on coffee-dto/coffee-dto-base/src/main/java/hu/icellmobilsoft/coffee/dto/adapter/UtcOffsetTimeXmlAdapter.java
> +        return OffsetTime.now().withOffsetSameInstant(ZoneOffset.UTC).toString();
hol hasznalod fel az offsetTime-ot? itt nem inkabb "offsetTime" kellene legyen az "OffsetTime.now()" helyett?

2021-09-27 07:10 UTC, rombow requested changes

2021-09-27 07:10 UTC, rombow commented on coffee-dto/coffee-dto-base/src/main/java/hu/icellmobilsoft/coffee/dto/adapter/UtcOffsetTimeXmlAdapter.java
> +        return OffsetTime.now().withOffsetSameInstant(ZoneOffset.UTC).toString();
tenyleg lemaradt

2021-09-27 11:38 UTC, bucherarnold submitted a review, later dismissed

2021-09-27 12:50 UTC, petrenyi-mark approved these changes

2021-09-27 13:10 UTC, rombow submitted a review, later dismissed

2021-09-27 13:38 UTC, czenczl approved these changes

2021-10-05 11:59 UTC, closed without merging