Feature/189 redis enhancement i
i-Cell-Mobilsoft-Open-Source/coffee pull request #190
Opened 2021-08-27 23:39 UTC by czenczl

- Optimalizált pool kezelés
- Egységes hibakezelés
- Egységes log

2021-08-30 06:23 UTC, martin-nagy commented on coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/manager/RedisManager.java
> +        return functionInfo.toString() + ")";
`functionInfo.append(")").toString()` hatékonyabb

2021-08-30 06:28 UTC, martin-nagy approved these changes

2021-08-30 06:59 UTC, vasizs commented on docs/common/module/coffee-module-redis.adoc
> +Bevezetésre került a `RedisManager` osztály és hozzá tartozó `RedisManagerProducer`. A producer legyártja a RedisManager-t a hívott configKey értékkel, ezzel elérhetővé válik a Jedis kikérése a Jedis
"akkkor"

2021-08-30 07:01 UTC, vasizs commented on docs/common/module/coffee-module-redis.adoc
> +A definiált metódusok Jedis funkciókat várnak amiket lefuttatnak, ez megtehető az initConnection() és closeConnection() használatával, vagy a runWithConnection metódusokon kereszül. Ez a megközelítés
"kereszül"

2021-08-30 07:07 UTC, vasizs commented on coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/manager/RedisManager.java
> +        String msg = MessageFormat.format(sb.toString(), functionInfo);
erre szükség van? a StringBuilder-ben már hozzá van fűzve a functionInfo

2021-08-30 07:13 UTC, vasizs approved these changes

2021-08-30 07:13 UTC, rombow requested changes
a migracios doksiba lecci egy mondatot hogy uj cucc ment bevezetesre

2021-08-30 07:59 UTC, martin-nagy approved these changes

2021-08-30 08:06 UTC, rombow commented on docs/migration/migration160to170.adoc
> +== Változások
ez uj cucc nem valtozas

2021-08-30 08:07 UTC, rombow approved these changes

2021-08-30 08:18 UTC, martin-nagy approved these changes

2021-08-30 08:19 UTC, petrenyi-mark submitted a review, later dismissed

2021-08-30 08:27 UTC, vasizs submitted a review, later dismissed

2021-08-30 12:03 UTC, martin-nagy approved these changes

2021-08-31 08:35 UTC, rombow approved these changes

2021-09-01 07:36 UTC, bucherarnold approved these changes

2021-09-01 07:38 UTC, merged