Feature/197 redis trace
i-Cell-Mobilsoft-Open-Source/coffee pull request #198
Opened 2021-09-24 11:42 UTC by czenczl

2021-09-27 07:18 UTC, bucherarnold commented on docs/common/core/coffee-cdi/trace.adoc
> +** A `@Traced` annotáció lehetővé teszi hogy metóduson definialjuk a trace-elhetőséget.
typo

2021-09-27 07:20 UTC, vasizs commented on coffee-module/coffee-module-mp/coffee-module-mp-opentracing/src/main/java/hu/icellmobilsoft/coffee/module/mp/opentracing/extension/RedisStreamOpenTraceInterceptor.java
> +        Tracer tracer = getTracer();
ctx null check?

2021-09-27 07:21 UTC, bucherarnold approved these changes

2021-09-27 07:21 UTC, vasizs commented on docs/common/core/coffee-cdi/trace.adoc
> +** `@RedisManagerTraced` annotáción keresztül a `@RedisManager` trace adatokat képes adni. A redis manager lambda hyvásainak lekezelésére jött létre, a bemenő paraméterek általánosan megadják a hívot
"hyvásainak"

2021-09-27 08:34 UTC, rombow requested changes

2021-09-27 08:34 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-opentracing/src/main/java/hu/icellmobilsoft/coffee/module/mp/opentracing/extension/BaseOpenTraceInterceptor.java
> +            return finish(ctx);
proceed

2021-09-27 12:19 UTC, petrenyi-mark requested changes

2021-09-27 12:19 UTC, petrenyi-mark commented on coffee-module/coffee-module-mp/coffee-module-mp-opentracing/src/main/java/hu/icellmobilsoft/coffee/module/mp/opentracing/extension/BaseOpenTraceInterceptor.java
> +        for (int i = 0; i < ctx.getParameters().length; i++) {
Nem kellene null check ctx, ctx.getParameters()?

2021-09-27 12:19 UTC, petrenyi-mark commented on coffee-module/coffee-module-mp/coffee-module-mp-opentracing/src/main/java/hu/icellmobilsoft/coffee/module/mp/opentracing/extension/BaseOpenTraceInterceptor.java
> +                for (int i = 0; i < ctx.getParameters().length; i++) {
kell ez a for? minden i-re fixen a contextParameterIndex indexen lévő érték állítódik?

2021-09-27 12:19 UTC, petrenyi-mark commented on docs/migration/migration160to170.adoc
> +A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.
`@Traced` átkerült más packegebe, azt lehet érdemes lenne beleírni

2021-09-28 12:33 UTC, rombow approved these changes

2021-09-28 12:33 UTC, rombow commented on docs/common/module/coffee-module-mp-opentracing.adoc
> +* Coffee kompatibilizás - lehetőséget biztosít hogy a coffee moduljai trace információkat szolgáltassanak. A benne lévő interceptor a coff:ee moduljait képes kezelni, továbbfejleszthető saját tagek b
kompatibilizás typo

2021-09-28 12:43 UTC, rombow approved these changes

2021-09-28 13:17 UTC, bucherarnold approved these changes

2021-09-29 07:27 UTC, petrenyi-mark approved these changes

2021-09-29 10:03 UTC, merged