#71 Az összes beépített exception-re egy közös általános exceptionMapper
i-Cell-Mobilsoft-Open-Source/coffee pull request #220
Opened 2021-12-02 12:17 UTC by Balazs-Joo

2021-12-02 18:22 UTC, rombow requested changes

2021-12-02 18:22 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultBaseExceptionMapper.java
> +@Provider
Ez nem lehet provider a keretrendszer szinten

2021-12-03 07:52 UTC, rombow requested changes

2021-12-03 07:52 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultBaseExceptionMapper.java
> +        } else if (e instanceof InvalidRequestException) {
Ez mar a 1.2.0 verzio ota deprecated, itt az ideje inkabb ki is szedni a kodbol komplett

2021-12-03 08:27 UTC, rombow approved these changes

2021-12-03 08:31 UTC, martin-nagy approved these changes

2021-12-05 22:51 UTC, bucherarnold approved these changes

2021-12-05 23:22 UTC, czenczl approved these changes

2021-12-06 08:28 UTC, merged