#216 CsvUtil nyelvesítés support
i-Cell-Mobilsoft-Open-Source/coffee pull request #221
Opened 2021-12-06 14:34 UTC by martin-nagy

closes #216 

Ahhoz, hogy a csv modul ne függjön a coffee-rest modultól, a coffee-rest-ből ki lett emelve saját modulba a lokalizáció és konfig kezelés.

2021-12-14 10:13 UTC, rombow requested changes

2021-12-14 10:13 UTC, rombow commented on coffee-configuration/pom.xml
> +			<groupId>javax</groupId>
jakarta

2021-12-14 10:13 UTC, rombow commented on coffee-module/coffee-module-localization/pom.xml
> +			<groupId>javax</groupId>
jakarta

2021-12-14 11:47 UTC, martin-nagy commented on docs/common/core/coffee-configuration.adoc
> +Az osztály segítségével lehetőség van típushelyes konfigurációk lekérdezésére.
A `ConfigurationHelper` pont most vettük ki a cache-t. A cache-elős változata az `ApplicationConfiguration`.

2021-12-14 13:13 UTC, rombow commented on docs/common/core/coffee-configuration.adoc
> +Az osztály segítségével lehetőség van típushelyes konfigurációk lekérdezésére.
jah tenyleg, de akkor van igy ertelme?

2021-12-14 13:14 UTC, rombow approved these changes

2021-12-14 13:24 UTC, martin-nagy commented on docs/common/core/coffee-configuration.adoc
> +Az osztály segítségével lehetőség van típushelyes konfigurációk lekérdezésére.
`getString`, `getInteger`... metódusokat ad a `getValue(String propertyName, Class<T> propertyType)` helyett, de akár ki is lehet venni

2021-12-17 08:08 UTC, bucherarnold approved these changes

2021-12-21 08:50 UTC, czenczl approved these changes

2021-12-21 10:35 UTC, merged