#302 cdi modul deprecate deltaspike
i-Cell-Mobilsoft-Open-Source/coffee pull request #303
Opened 2022-08-16 18:12 UTC by czenczl

deltaspike fuggoseg megszuntetese

2022-08-16 18:38 UTC, bucherarnold approved these changes

2022-08-17 06:08 UTC, speter555 approved these changes

2022-08-17 06:39 UTC, rombow requested changes

2022-08-17 06:39 UTC, rombow commented on coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/logger/LogProducer.java
> +    public static Instance<AppLogger> getAppLogger(Class<?> clazz) {
a bejovo class parameter nincs hasznaljva semmire, igy ez az egesz eleg ertelmetlen

2022-08-17 07:03 UTC, czenczl commented on coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/logger/LogProducer.java
> +    public static Instance<AppLogger> getAppLogger(Class<?> clazz) {
jap, itt előtte volt egy bug, a get() peldanynak volt logger setelve, de a hivo felnek kell setelnie, mert az mar egy masik peldany, az ezzel javult

2022-08-17 07:04 UTC, bucherarnold approved these changes

2022-08-17 07:21 UTC, rombow requested changes

2022-08-17 09:34 UTC, czenczl commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultLoggerClientRequestFilter.java
> -        LogProducer.getAppLogger(getClass()).get().info(msg.toString());
közben több problema is van, leakelunk, azt javitom még, at irom ezt a kezelest kicsit

2022-08-17 14:02 UTC, rombow approved these changes

2022-08-17 14:07 UTC, vasizs approved these changes

2022-08-19 08:18 UTC, petrenyi-mark approved these changes

2022-08-19 12:34 UTC, speter555 approved these changes

2022-08-20 19:41 UTC, merged