OSP-40
i-Cell-Mobilsoft-Open-Source/coffee pull request #310
Opened 2022-09-09 10:47 UTC by kovacsgpeter

Redis stream consumer vs producer kulcsolas szetvalasztasa #203- 1.12

2022-09-09 14:02 UTC, rombow requested changes

2022-09-09 14:02 UTC, rombow commented on coffee-module/coffee-module-redisstream/src/test/java/hu/icellmobilsoft/coffee/module/redisstream/StreamPublisherTest.java
> +class StreamPublisherTest {
https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/blob/master/coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/RedisConfigTest.java

egy ehhez hasonlo teszt is kellene, ami a StreamGroupConfig osztalyt veszi celba

2022-09-09 14:12 UTC, rombow commented
Valami projekten probaljuk le hogy minden rendben-e lessz

2022-09-12 06:56 UTC, bucherarnold commented on coffee-module/coffee-module-redisstream/src/test/java/hu/icellmobilsoft/coffee/module/redisstream/StreamPublisherTest.java
> +                    .enableDiscovery())
format

2022-09-12 13:36 UTC, kovacsgpeter commented
> Valami projekten probaljuk le hogy minden rendben-e lessz

Vaderen teszteltem fejlesztői tesztekkel egyelőre

2022-09-13 03:54 UTC, speter555 submitted a review, later dismissed

2022-09-13 03:55 UTC, speter555 commented
Esetleg az ilyen redis dolgokat testcontainer segítségével is tesztelhetnénk.

2022-09-19 09:21 UTC, rombow requested changes

2022-09-19 09:21 UTC, rombow commented on coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/consumer/RedisStreamConsumerExecutor.java
>          this.redisConfigKey = redisConfigKey;
ez a kulcs mostmar ertelmet veszti hogyha a stream konfigba kerul az ertek megszerzese

2022-09-19 09:21 UTC, rombow commented on coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/config/StreamGroupConfig.java
> +    public static final String CONNECTION = "stream.connection.key";
Ha ezt bevezetjuk, akkor a @RedisStreamProducer(configKey = "redis1", group = "streamconfig1") mukodese elveszti az ertelmet, es eleg lenne csak a group hasznalata benne

2022-09-19 09:21 UTC, rombow commented on docs/migration/migration1110to1120.adoc
> +        sampleGroup: #(1)
itt meg mindig benne maradtak a commentek

2022-09-27 05:52 UTC, kovacsgpeter commented
> Esetleg az ilyen redis dolgokat testcontainer segítségével is tesztelhetnénk.
köszi,
hozzáadtam

2022-09-27 05:52 UTC, closed without merging