#311 - TransactionHelper bevezetése
i-Cell-Mobilsoft-Open-Source/coffee pull request #313
Opened 2022-09-19 22:46 UTC by bcsabi

2022-09-20 06:07 UTC, speter555 commented on docs/migration/migration1110to1120.adoc
> +Így lehetőségünk van arra, hogy ha egy osztály első belépési pontja nincs tranzakcióban, de azon elül szeretnénk tranzakcióban futtatni egy kód részletet, akkor elegendő a kívánt részt kiemelni egy *
type `de azon elül` -> belül.

2022-09-20 06:08 UTC, speter555 approved these changes

2022-09-20 06:21 UTC, rombow requested changes

2022-09-20 06:21 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/helper/TransactionHelper.java
> +        if (isNullOrBlankAnyParameter(baseExceptionFunction, p1)) {
nem feltetlenul kell kenyszeriteni a not null parametereket. Ezek altalanos metodusok, barmilyen parameter kombinacioval lehetnek hasznalva.

2022-09-20 06:21 UTC, rombow commented on docs/migration/migration1110to1120.adoc
> +=== coffee-jpa
Ennek a leirasnak a tobbseget kiegeszitve egy peldaval rendes dokumentacioba kellene rakni. Itt a migracios leirasnal csak 1 mondatban emliteni hogy letrejott es linkelni a leirasra

2022-09-22 08:29 UTC, rombow approved these changes

2022-09-22 08:31 UTC, bucherarnold approved these changes

2022-09-22 08:33 UTC, martin-nagy approved these changes

2022-09-22 08:50 UTC, speter555 approved these changes

2022-09-22 09:21 UTC, vasizs approved these changes

2022-09-22 09:22 UTC, petrenyi-mark approved these changes

2022-09-22 09:23 UTC, merged