#315 - BatchService "cannot cast 'java.util.Date' to 'java.sql.Timestamp'" hiba
i-Cell-Mobilsoft-Open-Source/coffee pull request #316
Opened 2022-09-26 20:45 UTC by bcsabi

- timestamp érték instanceof szerinti beállítása
- timestamp és temporal különszeparálása

2022-09-27 03:38 UTC, speter555 commented
Doksizást is írd meg kérlek!

2022-09-27 06:50 UTC, rombow requested changes

2022-09-27 06:50 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
> +        if (type instanceof TimestampType) {
keszics leccives egy unit tesztet ami minden ismert datum tipust atfuttat a parametereken

2022-09-27 06:50 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
> +    protected void setTemporalPsObject(PreparedStatement ps, int parameterIndex, Object value) throws SQLException {
ez a kod struktura szamomra annyibol fura hogy nem sajat maga donti el hogy csinalja a `ps.setObject` hivast, es elegge szet van szorva a vegrehajtasi logika. Ez a kod olvasasanal tobb metodus olvasasaba kenyszerit ami mindenkeppen lassitja a kod atlathatosagat

2022-10-17 10:55 UTC, rombow requested changes

2022-10-17 10:55 UTC, rombow commented on docs/migration/migration1110to1120.adoc
> +=== coffee-jpa
ez a merge konflict feloldas nem jott ossze :)

2022-10-17 10:59 UTC, rombow approved these changes

2022-10-17 11:12 UTC, bucherarnold approved these changes

2022-10-17 11:19 UTC, martin-nagy approved these changes

2022-10-17 11:21 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
> +            Time time = new Time(((Date) value).getTime());
@sonatype-lift ignore

2022-10-17 11:21 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
> +            return Optional.of(new Timestamp(((Date) value).getTime()));
@sonatype-lift ignore

2022-10-17 11:43 UTC, vasizs approved these changes

2022-10-17 11:46 UTC, czenczl approved these changes

2022-10-17 11:48 UTC, merged