#338 JsonUtil-ba YearMonth type adapter
i-Cell-Mobilsoft-Open-Source/coffee pull request #339
Opened 2022-11-02 09:46 UTC by janosboroczki

2022-11-02 09:48 UTC, martin-nagy commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/YearMonthConverter.java
> +    /** {@inheritDoc} */
@inheritDoc önmagában felesleges, az override-olt metódus javadoc kiegészítéséhez lehet használni

2022-11-02 09:50 UTC, martin-nagy commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/JsonUtil.java
> +                .registerTypeAdapter(YearMonth.class, new YearMonthConverter()) //
Migrációs doksiba minden issue esetén legyen bejegyzés (docs/migration/migration*.adoc)

2022-11-02 10:00 UTC, rombow requested changes

2022-11-02 10:00 UTC, rombow commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/YearMonthConverter.java
> +    private void handleNotJsonPrimitive(JsonElement json) {
erre a reszre is jo lenne teszt

2022-11-02 12:38 UTC, martin-nagy approved these changes

2022-11-10 12:06 UTC, rombow approved these changes

2022-11-10 13:01 UTC, vasizs approved these changes

2022-11-10 13:10 UTC, merged