#314 - InvalidParameterException bevezetése
i-Cell-Mobilsoft-Open-Source/coffee pull request #343
Opened 2022-11-15 23:07 UTC by bcsabi

- InvalidParameterException bevezetése és használata
- JaxbTool és IXsdHelper metódusoknál BaseException dobása XsdProcessingException helyett
- BaseProcessingException bevezetése és használata
- XsdProcessingExceptionWrapper törlése

2022-11-16 09:10 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/exception/BaseProcessingException.java
> +public class BaseProcessingException extends ProcessingException implements BaseExceptionWrapper<BaseException> {
Ennel le kell probalni hogy a XsdProcessingException kezeles megmarad olyannak-e ahogy azt kell a DefaultBaseExceptionMapper osztalyban. Ez egy probelmakat okozhat ha ez megvaltozik

2022-11-16 09:10 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/exception/BaseProcessingException.java
> +public class BaseProcessingException extends ProcessingException implements BaseExceptionWrapper<BaseException> {
A Wrapper postfix jo lenne ha megmaradna

2022-11-16 09:14 UTC, rombow requested changes

2022-11-16 09:14 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/service/BaseService.java
> -    public static BaseException newInvalidParameterException(String msg) {
Ezt elso korben deprecated-re kell jelolni, mert eleg nagy munkat fog okozni a projekteken ha toroljuk...

2022-11-16 09:27 UTC, bcsabi commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/exception/BaseProcessingException.java
> +public class BaseProcessingException extends ProcessingException implements BaseExceptionWrapper<BaseException> {
Leteszteltem MR kiírás előtt projekten, megmaradt szépen a feldolgozás.

2022-11-20 13:18 UTC, bucherarnold approved these changes

2022-11-21 08:11 UTC, rombow approved these changes

2022-11-21 08:18 UTC, rombow commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/service/BaseService.java
>      public static BaseException newInvalidParameterException(String msg) {
@sonatype-lift ignore

2022-11-21 08:22 UTC, martin-nagy approved these changes

2022-11-21 09:08 UTC, czenczl approved these changes

2022-11-25 07:48 UTC, merged