Bugfix/292 requestresponselogger memoria tuning v2
i-Cell-Mobilsoft-Open-Source/coffee pull request #379
Opened 2023-01-18 09:22 UTC by mate-biro

Teszt:

- repeat count: 20
- testPostStream
- RandomInputStream: 209715200 byte = 209.7152 Mb

Eredmény:

**BaseRestLogger**

test start | Nov 24, 2023 5:41:51 PM
test end | Nov 24, 2023 5:46:51 PM

![BaseRestLogger_v2](https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/assets/72201116/f23c381c-4fa4-458b-8b3e-29412f670f3c)

**Optimized BaseRestLogger**

test start | Nov 24, 2023 5:24:19 PM
test end | Nov 24, 2023 5:25:22 PM

![BaseRestLogger_opt_v2](https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/assets/72201116/3f80122b-b3c8-4f6b-a8cb-896cbe2cc055)

2023-06-08 20:54 UTC, bucherarnold approved these changes

2023-09-20 10:43 UTC, Balazs-Joo approved these changes

2023-09-20 10:47 UTC, Balazs-Joo commented
Lehet tudni valamit erről a javításról és a párjáról?
https://github.com/i-Cell-Mobilsoft-Open-Source/coffee/pull/376

2023-09-20 15:08 UTC, mate-biro commented
> Lehet tudni valamit erről a javításról és a párjáról? #376

igen, a közeljövőben tervezek visszatérni a feladatra és befejezni. Még az alábbi feladatok vannak vele:

- [ ] feltétel refakt: ha nincs fent a log spec annotáció, akkor tudjuk, hogy mit jelent
eredetileg ez volt a szándék, hogyha nincs rajta az annotáció és octet stream, akkor korlátozunk (xml-t meg json-t csak akkor korlátozzunk, ha fent van az annotáció)
- [ ] firstReadCycle flag felülvizsgálás: miért read-el újra a MessageBodyReader
- [ ] felülírt Stream osztályok-ban a logika legyen egységesebb, átláthatóbb
- [ ] logolás logika kiszervezése

2023-10-16 06:48 UTC, rombow requested changes

2023-10-16 06:48 UTC, rombow commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/stream/RequestLoggerInputStream.java
> +@Vetoed
vetoed default mar nem kell

2023-10-16 06:48 UTC, rombow commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/stream/RequestLoggerInputStream.java
> + * @since 1.14.0
verzioszamok nem passzolnak a migracios leirasnal sem

2023-11-24 15:40 UTC, rombow approved these changes

2023-11-25 04:57 UTC, bucherarnold approved these changes

2023-11-25 09:45 UTC, czenczl approved these changes

2023-11-25 10:19 UTC, merged