Feature/254 http status code kezeles
i-Cell-Mobilsoft-Open-Source/coffee pull request #410
Opened 2023-02-22 08:47 UTC by gabor-balazs

2023-02-22 09:03 UTC, rombow approved these changes

2023-02-22 11:00 UTC, czenczl submitted a review, later dismissed

2023-02-22 11:08 UTC, bucherarnold approved these changes

2023-02-22 12:38 UTC, petrenyi-mark commented on docs/migration/migrationTo2_0_0.adoc
> +* Az eddigi exception státuszkód kezelés megtartásához a projekteken saját ExceptionMapper létrehozása szükséges.
BaseService hívásoknál ha van meglévő OptimisticLockException-re catch, azt ha jól látom cserélni kell a coffee-sra, ezt ide jó lenne bele írni

2023-03-02 12:38 UTC, petrenyi-mark submitted a review, later dismissed

2023-03-02 13:11 UTC, czenczl submitted a review, later dismissed

2023-03-02 22:47 UTC, bucherarnold submitted a review, later dismissed

2023-03-03 07:47 UTC, rombow approved these changes

2023-03-03 09:51 UTC, speter555 approved these changes

2023-03-13 10:53 UTC, vasizs submitted a review, later dismissed

2023-07-04 15:27 UTC, magyari-adam commented on coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/service/BaseService.java
> +import javax.persistence.OptimisticLockException;
Ez rendben van?

2023-07-06 09:08 UTC, magyari-adam approved these changes

2023-07-06 09:18 UTC, rombow submitted a review, later dismissed

2023-07-07 14:23 UTC, cserhatit commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
részemről lehetne az is én csak kijavítottam azt a hibát, ami miatt nem futott le a CI job :)
@gabor-balazs ?

2023-07-07 14:24 UTC, cserhatit commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
de amugy azert, mert ez volt a leirasban gondolom :)

"Technikai hiba - optimistic lock - 518 (jelenleg 500)"

2023-07-10 06:11 UTC, speter555 commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
azért nem 4x mert a 4x kliens hibákra utal, míg az optimistic lock technikai oldalon keletkezik, annó ezért választottuk ezt.

2023-07-10 06:18 UTC, martin-nagy commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
Okés. Azért annyira nem érzem a server hibájának, hogy a kliens régi verziójú adatot küld :)

2023-07-10 06:59 UTC, gabor-balazs commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
> de amugy azert, mert ez volt a leirasban gondolom :)
> 
> "Technikai hiba - optimistic lock - 518 (jelenleg 500)"

Igen a feladat leírást követtem.

2023-07-10 07:11 UTC, rombow commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
Ezeket a kodokat kozosen valasztottuk, es alapvetoen a problema hogy a HTTP statusz kodok inkabb a protokolrol szolnak, arra adnak valami lehetosegeket es nagyon altalanosak. Mindenki mashogy ertelmezi oket. Peldaul a 409 konretan CONFLICT (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) es irjak is hogy `For example, you may get a 409 response when uploading a file that is older than the existing one on the server, resulting in a version control conflict.` viszont uzleti ertelemben ahogy nalunk keletkezik ez valid input es technikailag a DB fogja elszallitani (nem is tudunk ra keszulni). Ha a request resze lenne kotelezoen az adat verzioszama, akkor mar elegge mas helyzetrol beszelhetunk es a 409 akar jogos lehet.

2023-07-10 07:12 UTC, rombow approved these changes

2023-07-10 07:16 UTC, martin-nagy approved these changes

2023-07-10 07:56 UTC, czenczl commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/enums/HttpStatus.java
> +    OPTIMISTIC_LOCK(518, "Optimistic Lock");
még mielott bemegy azt is tisztázni kellene hogyan terítjük az infot, belsős dokumentaciokat is érinteni fogja nem csak az opensourcet

2023-07-14 11:32 UTC, rombow requested changes

2023-07-17 06:39 UTC, martin-nagy approved these changes

2023-07-17 06:44 UTC, rombow approved these changes

2023-07-17 07:26 UTC, petrenyi-mark approved these changes

2023-07-17 07:32 UTC, merged