536 AbstractEntity toString fix
i-Cell-Mobilsoft-Open-Source/coffee pull request #537
Opened 2023-10-03 10:40 UTC by attila-kiss-it

2023-10-03 11:30 UTC, rombow requested changes
release notes plz hogy mi tortent

2023-10-03 11:30 UTC, rombow commented on coffee-bom/pom.xml
> +        <version.commons-logging>1.2</version.commons-logging>
space vs tab hasznalata leccives ne legyen keverve

2023-10-03 11:59 UTC, attila-kiss-it commented on coffee-bom/pom.xml
> +        <version.commons-logging>1.2</version.commons-logging>
Az új formázási szabályok szerint space kell és csak az új kódra kell alkalmazni. Itt mi az elvárt?

2023-10-04 06:58 UTC, rombow commented on coffee-bom/pom.xml
> +        <version.commons-logging>1.2</version.commons-logging>
Ha uj a file akkor a szabalyok szerint, ha meglevo file akkor ugy ahogy a kod tobbsege van. Vagy atformazni a szabalyokra de lehetoleg akkor nem kodvaltozassal, masik MR-en

2023-10-09 19:23 UTC, bcsabi commented on coffee-model/coffee-model-base/src/test/java/hu/icellmobilsoft/coffee/model/base/AbstractEntityTest.java
> +        String actualToStringValue = entity.toString();
Ez inkább a `when` részbe illene

2023-10-16 09:10 UTC, rombow approved these changes

2023-10-16 09:56 UTC, czenczl approved these changes

2023-10-16 11:34 UTC, Balazs-Joo approved these changes

2023-10-16 12:29 UTC, merged