Feature/564 ignore versionreader
i-Cell-Mobilsoft-Open-Source/coffee pull request #565
Opened 2024-01-09 10:15 UTC by cserhatit

2024-01-09 10:41 UTC, petrenyi-mark requested changes

2024-01-09 10:41 UTC, petrenyi-mark commented on docs/hu/migration/migration240to250.adoc
> -(`hu.icellmobilsoft.coffee.module.redisstream.bootstrap.ConsumerLifeCycleManager`)
itt valami conflict félrement

2024-01-09 10:52 UTC, petrenyi-mark submitted a review, later dismissed

2024-01-09 11:46 UTC, rombow approved these changes

2024-01-09 13:44 UTC, mate-biro approved these changes

2024-01-10 08:03 UTC, rombow approved these changes

2024-01-10 08:20 UTC, martin-nagy commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/JaxbTool.java
> +        if (validateXMLs != null && Arrays.stream(validateXMLs).anyMatch(e -> e.version().include().length > 0)) {
Itt nem lehet valami null? pl e.version().include()

2024-01-10 08:20 UTC, martin-nagy approved these changes

2024-01-10 08:22 UTC, cserhatit commented on coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/JaxbTool.java
> +        if (validateXMLs != null && Arrays.stream(validateXMLs).anyMatch(e -> e.version().include().length > 0)) {
nem lehet

2024-01-10 08:23 UTC, merged