#55 mp-restclient DefaultBaseExceptionResponseExceptionMapper letrehozasa
i-Cell-Mobilsoft-Open-Source/coffee pull request #77
Opened 2020-10-01 14:39 UTC by magyari-adam

2020-10-01 15:05 UTC, rombow requested changes

2020-10-01 15:05 UTC, rombow commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/exception/FaultTypeParser.java
> +public class FaultTypeParser {
ez a parser kimondottan a microprofile-rest-client számára kell, tegyük léccives oda

2020-10-01 15:05 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultBaseExceptionResponseExceptionMapper.java
> +                return new BONotFoundException(
ez az általános exception nem elég sajnos jelen esetben, mert pont az a fontos információ veszik el belőle, ami a dto-ban ott van, melyik service-ből származik az exception, mi volt a stacktrace. Ezekkel az infókkal pont erre a célra lett bővítve a BaseExceptionResultType. Ezeken az infókat ki kell nyerni belőle és azt kell kidobni

2020-10-06 10:33 UTC, magyari-adam commented on coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/exception/FaultTypeParser.java
> +public class FaultTypeParser {
átmozgatva

2020-10-06 11:41 UTC, rombow requested changes

2020-10-06 11:41 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/ResponseException.java
> +public class ResponseException extends BaseException {
Így túl általános, valami konkrétabb kellene például RestClientResponseException vagy hasonló

2020-10-06 11:41 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/ResponseException.java
> +    public static ResponseException fromExceptionResult(BaseExceptionResultType baseExceptionResultType) {
doc

2020-10-06 11:41 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/FaultTypeParser.java
> +    public static Enum<?> parseFaultType(String faultTypeString) {
doc lemarat még régebről, leccives most pótoljuk

2020-10-06 11:42 UTC, rombow commented
migracios doksi-ba is keruljon valami leiras leccives

2020-10-06 14:32 UTC, magyari-adam commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/ResponseException.java
> +public class ResponseException extends BaseException {
átnevezve

2020-10-06 14:32 UTC, magyari-adam commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/ResponseException.java
> +    public static ResponseException fromExceptionResult(BaseExceptionResultType baseExceptionResultType) {
pótolva

2020-10-06 14:38 UTC, rombow approved these changes

2020-10-06 14:38 UTC, rombow commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/RestClientResponseException.java
> +        RestClientResponseException exception = new RestClientResponseException(FaultTypeParser.parseFaultType(baseExceptionResultType.getFaultType()), baseExceptionResultType.getMessage());
NPE check hiányzik

2020-10-06 14:47 UTC, magyari-adam commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/RestClientResponseException.java
> +        RestClientResponseException exception = new RestClientResponseException(FaultTypeParser.parseFaultType(baseExceptionResultType.getFaultType()), baseExceptionResultType.getMessage());
pótolva

2020-10-06 16:18 UTC, rombow approved these changes

2020-10-07 09:34 UTC, bucherarnold commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/RestClientResponseException.java
> +public class RestClientResponseException extends BaseException {
@Vetoed?

2020-10-07 09:34 UTC, bucherarnold approved these changes

2020-10-07 11:22 UTC, vasizs approved these changes

2020-10-07 11:33 UTC, czenczl approved these changes

2020-10-07 12:21 UTC, magyari-adam commented on coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/RestClientResponseException.java
> +public class RestClientResponseException extends BaseException {
Exception-ön nem gondolom szükségesnek.

2020-10-07 12:21 UTC, merged