#72 common.xsd TimestampType pattern bővítése
i-Cell-Mobilsoft-Open-Source/coffee pull request #82
Opened 2020-10-05 12:53 UTC by jhamrak

2020-10-05 13:10 UTC, rombow requested changes

2020-10-05 13:10 UTC, rombow commented on coffee-dto/coffee-dto-xsd/src/main/resources/xsd/hu/icellmobilsoft/coffee/dto/common/common.xsd
> +				value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,6})?Z" />
volt meg egy regi hibank a milisecnel, a helyes pattern `\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,6})?Z`

2020-10-05 14:37 UTC, petrenyi-mark submitted a review, later dismissed

2020-10-05 14:49 UTC, rombow commented on coffee-dto/coffee-dto-xsd/src/main/resources/xsd/hu/icellmobilsoft/coffee/dto/common/common.xsd
> +				value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{1,6})?Z" />
migrációs doksiba is vedd fel légyszíves a pattern változást

2020-10-05 14:49 UTC, vasizs submitted a review, later dismissed

2020-10-05 14:50 UTC, bucherarnold submitted a review, later dismissed

2020-10-05 17:44 UTC, balazsbakos submitted a review, later dismissed

2020-10-06 06:22 UTC, czenczl submitted a review, later dismissed

2020-10-08 07:24 UTC, rombow approved these changes

2020-10-08 09:44 UTC, balazsbakos approved these changes

2020-10-08 09:45 UTC, csabasuli approved these changes

2020-10-08 10:39 UTC, bucherarnold approved these changes

2020-10-08 10:41 UTC, rombow approved these changes

2020-10-08 10:56 UTC, czenczl approved these changes

2020-10-08 11:32 UTC, petrenyi-mark approved these changes

2020-10-08 12:06 UTC, merged